/** The types of modifiers existing for monster types */
export enum MonsterTypeModifierType {
    TraitApplied = "traitApplied",
    IncreasedDamage = "increasedDamage",
    DecreasedDamage = "decreasedDamage",
    IncreasedDamageTaken = "increasedDamageTaken",
    DecreasedDamageTaken = "decreasedDamageTaken",
    IncreasedMaxHitPercent = "increasedMaxHitPercent",
    DecreasedMaxHitPercent = "decreasedMaxHitPercent",
    IncreasedMaxHitFlat = "increasedMaxHitFlat",
    DecreasedMaxHitFlat = "decreasedMaxHitFlat",
    IncreasedMinHitBasedOnMaxHit = "increasedMinHitBasedOnMaxHit",
    DecreasedMinHitBasedOnMaxHit = "decreasedMinHitBasedOnMaxHit",
    IncreasedFlatMinHit = "increasedFlatMinHit",
    DecreasedFlatMinHit = "decreasedFlatMinHit",
    IncreasedGlobalAccuracy = "increasedGlobalAccuracy",
    DecreasedGlobalAccuracy = "decreasedGlobalAccuracy",
    IncreasedDamageReduction = "increasedDamageReduction",
    DecreasedDamageReduction = "decreasedDamageReduction",
    IncreasedChanceToApplyTraitInfiniteOnSpawn = "increasedChanceToApplyTraitInfiniteOnSpawn",
    DecreasedChanceToApplyTraitInfiniteOnSpawn = "decreasedChanceToApplyTraitInfiniteOnSpawn",
    ApplyTraitTurnsOnSpawn = "applyTraitTurnsOnSpawn",
    IncreasedChanceToApplyTrait = "increasedChanceToApplyTrait",
    DecreasedChanceToApplyTrait = "decreasedChanceToApplyTrait",
    ApplyTraitTurns = "applyTraitTurns"
}